#!/bin/bash -e

# Conserity : Get the password from remote server
# Copyright (C) 2019  BitLogiK
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

clientIPs=`cat $1`
shares=""
for i in $clientIPs
do
  share="$(wget -T 4 -t 2 -O - https://$i 2>/dev/null)" || :
  if [[ $share =~ ^[a-zA-Z0-9+/]{44}$ ]]; then
    shares="$shares $share"
  fi
done
eval "$(dirname $0)/shamir/recover_secret.py $shares"

